# Generated by Django 5.1.5 on 2025-01-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='live_audio',
            field=models.FileField(blank=True, null=True, upload_to='live_audios/'),
        ),
        migrations.AddField(
            model_name='message',
            name='live_picture',
            field=models.ImageField(blank=True, null=True, upload_to='live_pictures/'),
        ),
        migrations.AddField(
            model_name='message',
            name='live_video',
            field=models.FileField(blank=True, null=True, upload_to='live_videos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('live_picture', 'Live Picture'), ('live_video', 'Live Video'), ('live_audio', 'Live Audio')], default='text', max_length=15),
        ),
    ]
