# Generated by Django 5.1.5 on 2025-01-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_live_audio_message_live_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='live_audio',
        ),
        migrations.RemoveField(
            model_name='message',
            name='live_picture',
        ),
        migrations.RemoveField(
            model_name='message',
            name='live_video',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('media', 'Media')], default='text', max_length=10),
        ),
    ]
